name: tox
description: 'Installs and runs tox on the current runner'
inputs:
  python-version:
    description: 'Python version'
    required: false
    default: "3.7 - 3.12"
  plugins:
    description: 'tox plugins'
    required: false
    default: "tox"
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      id: python
      with:
        python-version: "${{ inputs.python-version }}"
        update-environment: false
    - run: >
        pipx install
        --python '${{ steps.python.outputs.python-path }}'
        tox
        --preinstall
        "${{ inputs.plugins }}"
      shell: bash
    - run: >
        pipx run
        --python '${{ steps.python.outputs.python-path }}'
        tox
        2>&1
      shell: bash